import type { ChatModelOption } from "@/lib/chat-models";

export type ProviderProtocol =
  | "openai-compatible"
  | "anthropic"
  | "gemini"
  | "cohere"
  | "azure-openai"
  | "vertex-openai"
  | "bedrock-converse"
  | "ollama";

export type ProviderCategory =
  | "global"
  | "aggregator"
  | "cloud"
  | "china"
  | "local"
  | "custom";

export type ProviderAuthType =
  | "bearer"
  | "x-api-key"
  | "google-api-key"
  | "aws-sigv4"
  | "none";

export type ProviderCapabilities = {
  chat: boolean;
  models: boolean;
  vision?: boolean;
  webSearch?: boolean;
  tools?: boolean;
  local?: boolean;
};

export type ProviderDefinition = {
  id: string;
  name: string;
  category: ProviderCategory;
  protocol: ProviderProtocol;
  baseURL: string;
  modelsEndpoint: string;
  chatEndpoint: string;
  defaultModel: string;
  envKey?: string;
  authType: ProviderAuthType;
  capabilities: ProviderCapabilities;
  docsUrl: string;
  fallbackModels: ChatModelOption[];
  note?: string;
};

function models(...items: Array<[string, string?, Partial<ChatModelOption>?]>): ChatModelOption[] {
  return items.map(([id, label, extra]) => ({ id, label: label || id, ...extra }));
}

export const PROVIDER_DEFINITIONS: ProviderDefinition[] = [
  {
    id: "openai",
    name: "OpenAI",
    category: "global",
    protocol: "openai-compatible",
    baseURL: "https://api.openai.com/v1",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "gpt-4o-mini",
    envKey: "OPENAI_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true, vision: true, tools: true },
    docsUrl: "https://platform.openai.com/docs/api-reference/models/list",
    fallbackModels: models(["gpt-4o-mini", "GPT-4o mini", { vision: true }], ["gpt-4o", "GPT-4o", { vision: true }]),
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    category: "global",
    protocol: "openai-compatible",
    baseURL: "https://api.deepseek.com/v1",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "deepseek-chat",
    envKey: "DEEPSEEK_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true },
    docsUrl: "https://api-docs.deepseek.com/",
    fallbackModels: models(["deepseek-chat", "DeepSeek Chat"], ["deepseek-reasoner", "DeepSeek Reasoner"]),
  },
  {
    id: "kimi",
    name: "Kimi / Moonshot",
    category: "china",
    protocol: "openai-compatible",
    baseURL: "https://api.moonshot.ai/v1",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "kimi-k2.6",
    envKey: "KIMI_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true, tools: true },
    docsUrl: "https://platform.kimi.ai/docs/api/overview",
    fallbackModels: models(["kimi-k2.6", "Kimi K2.6"], ["moonshot-v1-8k", "Moonshot v1 8K"]),
  },
  {
    id: "qwen",
    name: "Qwen / DashScope",
    category: "china",
    protocol: "openai-compatible",
    baseURL: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "qwen-plus",
    envKey: "QWEN_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true, vision: true, tools: true },
    docsUrl: "https://help.aliyun.com/zh/model-studio/compatibility-of-openai-with-dashscope",
    fallbackModels: models(["qwen-plus", "Qwen Plus"], ["qwen-turbo", "Qwen Turbo"], ["qwen-max", "Qwen Max"]),
  },
  {
    id: "claude",
    name: "Claude / Anthropic",
    category: "global",
    protocol: "anthropic",
    baseURL: "https://api.anthropic.com/v1",
    modelsEndpoint: "/models",
    chatEndpoint: "/messages",
    defaultModel: "claude-3-5-sonnet-20241022",
    envKey: "CLAUDE_API_KEY",
    authType: "x-api-key",
    capabilities: { chat: true, models: true, vision: true, tools: true },
    docsUrl: "https://docs.anthropic.com/en/api/messages",
    fallbackModels: models(["claude-3-5-sonnet-20241022", "Claude 3.5 Sonnet", { vision: true }]),
  },
  {
    id: "gemini",
    name: "Gemini",
    category: "global",
    protocol: "gemini",
    baseURL: "https://generativelanguage.googleapis.com/v1beta",
    modelsEndpoint: "/models",
    chatEndpoint: "/models/{model}:generateContent",
    defaultModel: "gemini-1.5-flash",
    envKey: "GEMINI_API_KEY",
    authType: "google-api-key",
    capabilities: { chat: true, models: true, vision: true },
    docsUrl: "https://ai.google.dev/gemini-api/docs",
    fallbackModels: models(["gemini-1.5-flash", "Gemini 1.5 Flash", { vision: true }], ["gemini-1.5-pro", "Gemini 1.5 Pro", { vision: true }]),
  },
  {
    id: "glm",
    name: "GLM / Zhipu",
    category: "china",
    protocol: "openai-compatible",
    baseURL: "https://open.bigmodel.cn/api/paas/v4",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "glm-4-flash",
    envKey: "GLM_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true, tools: true },
    docsUrl: "https://docs.bigmodel.cn/api-reference",
    fallbackModels: models(["glm-4-flash", "GLM-4 Flash"], ["glm-4", "GLM-4"]),
  },
  {
    id: "ollama",
    name: "Ollama",
    category: "local",
    protocol: "ollama",
    baseURL: "http://localhost:11434",
    modelsEndpoint: "/api/tags",
    chatEndpoint: "/api/chat",
    defaultModel: "llama3.1",
    envKey: "OLLAMA_BASE_URL",
    authType: "none",
    capabilities: { chat: true, models: true, local: true },
    docsUrl: "https://github.com/ollama/ollama/blob/main/docs/api.md",
    fallbackModels: models(["llama3.1", "Llama 3.1"]),
  },
  {
    id: "github_models",
    name: "GitHub Models",
    category: "aggregator",
    protocol: "openai-compatible",
    baseURL: "https://models.github.ai/inference",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "openai/gpt-4o-mini",
    envKey: "GITHUB_MODELS_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true, tools: true },
    docsUrl: "https://docs.github.com/en/github-models",
    fallbackModels: models(["openai/gpt-4o-mini", "OpenAI GPT-4o mini"], ["meta/Llama-3.3-70B-Instruct", "Llama 3.3 70B"]),
  },
  {
    id: "minimax",
    name: "MiniMax",
    category: "china",
    protocol: "openai-compatible",
    baseURL: "https://api.minimax.io/v1",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "MiniMax-M1",
    envKey: "MINIMAX_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true },
    docsUrl: "https://platform.minimax.io/docs/api-reference/text-openai-api",
    fallbackModels: models(["MiniMax-M1", "MiniMax M1"]),
  },
  {
    id: "nvidia",
    name: "NVIDIA NIM",
    category: "aggregator",
    protocol: "openai-compatible",
    baseURL: "https://integrate.api.nvidia.com/v1",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "meta/llama-3.1-8b-instruct",
    envKey: "NVIDIA_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true },
    docsUrl: "https://docs.nvidia.com/nim/large-language-models/latest/reference/api-reference.html",
    fallbackModels: models(["meta/llama-3.1-8b-instruct", "Llama 3.1 8B"]),
  },
  {
    id: "siliconflow",
    name: "SiliconFlow",
    category: "aggregator",
    protocol: "openai-compatible",
    baseURL: "https://api.siliconflow.cn/v1",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "Qwen/Qwen2.5-7B-Instruct",
    envKey: "SILICONFLOW_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true },
    docsUrl: "https://docs.siliconflow.com/en/api-reference/models/get-model-list",
    fallbackModels: models(["Qwen/Qwen2.5-7B-Instruct", "Qwen2.5 7B"], ["deepseek-ai/DeepSeek-V3", "DeepSeek V3"]),
  },
  {
    id: "volcengine",
    name: "Volcengine Ark",
    category: "china",
    protocol: "openai-compatible",
    baseURL: "https://ark.cn-beijing.volces.com/api/v3",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "doubao-seed-1-6",
    envKey: "VOLCENGINE_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true, vision: true },
    docsUrl: "https://www.volcengine.com/docs/82379/1494384",
    fallbackModels: models(["doubao-seed-1-6", "Doubao Seed 1.6"]),
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    category: "aggregator",
    protocol: "openai-compatible",
    baseURL: "https://openrouter.ai/api/v1",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "openai/gpt-4o-mini",
    envKey: "OPENROUTER_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true, vision: true, tools: true },
    docsUrl: "https://openrouter.ai/docs/api-reference/overview",
    fallbackModels: models(["openai/gpt-4o-mini", "OpenAI GPT-4o mini"], ["anthropic/claude-3.5-sonnet", "Claude 3.5 Sonnet"]),
  },
  {
    id: "custom_openai",
    name: "Custom OpenAI-compatible",
    category: "custom",
    protocol: "openai-compatible",
    baseURL: "",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "gpt-4o-mini",
    envKey: "CUSTOM_OPENAI_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true, vision: true, tools: true },
    docsUrl: "https://platform.openai.com/docs/api-reference/chat",
    fallbackModels: models(["gpt-4o-mini", "Default model"]),
  },
  {
    id: "mistral",
    name: "Mistral",
    category: "global",
    protocol: "openai-compatible",
    baseURL: "https://api.mistral.ai/v1",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "mistral-large-latest",
    envKey: "MISTRAL_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true, tools: true },
    docsUrl: "https://docs.mistral.ai/api",
    fallbackModels: models(["mistral-large-latest", "Mistral Large"], ["mistral-small-latest", "Mistral Small"]),
  },
  {
    id: "groq",
    name: "Groq",
    category: "aggregator",
    protocol: "openai-compatible",
    baseURL: "https://api.groq.com/openai/v1",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "llama-3.3-70b-versatile",
    envKey: "GROQ_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true },
    docsUrl: "https://console.groq.com/docs/api-reference",
    fallbackModels: models(["llama-3.3-70b-versatile", "Llama 3.3 70B"], ["openai/gpt-oss-120b", "GPT-OSS 120B"]),
  },
  {
    id: "together",
    name: "Together AI",
    category: "aggregator",
    protocol: "openai-compatible",
    baseURL: "https://api.together.xyz/v1",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
    envKey: "TOGETHER_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true },
    docsUrl: "https://docs.together.ai/reference/chat-completions-1",
    fallbackModels: models(["meta-llama/Llama-3.3-70B-Instruct-Turbo", "Llama 3.3 70B Turbo"]),
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    category: "aggregator",
    protocol: "openai-compatible",
    baseURL: "https://api.fireworks.ai/inference/v1",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "accounts/fireworks/models/llama-v3p1-8b-instruct",
    envKey: "FIREWORKS_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true },
    docsUrl: "https://docs.fireworks.ai/tools-sdks/openai-compatibility",
    fallbackModels: models(["accounts/fireworks/models/llama-v3p1-8b-instruct", "Llama 3.1 8B"]),
  },
  {
    id: "perplexity",
    name: "Perplexity",
    category: "global",
    protocol: "openai-compatible",
    baseURL: "https://api.perplexity.ai/v1",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "sonar",
    envKey: "PERPLEXITY_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true, webSearch: true },
    docsUrl: "https://docs.perplexity.ai/docs/grounded-llm/openai-compatibility",
    fallbackModels: models(["sonar", "Sonar"], ["sonar-pro", "Sonar Pro"]),
  },
  {
    id: "xai",
    name: "xAI",
    category: "global",
    protocol: "openai-compatible",
    baseURL: "https://api.x.ai/v1",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "grok-4.3",
    envKey: "XAI_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true, vision: true },
    docsUrl: "https://docs.x.ai/docs/guides/chat-completions",
    fallbackModels: models(["grok-4.3", "Grok 4.3"]),
  },
  {
    id: "cerebras",
    name: "Cerebras",
    category: "aggregator",
    protocol: "openai-compatible",
    baseURL: "https://api.cerebras.ai/v1",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "gpt-oss-120b",
    envKey: "CEREBRAS_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true },
    docsUrl: "https://inference-docs.cerebras.ai/api-reference",
    fallbackModels: models(["gpt-oss-120b", "GPT-OSS 120B"], ["llama-3.3-70b", "Llama 3.3 70B"]),
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    category: "aggregator",
    protocol: "openai-compatible",
    baseURL: "https://router.huggingface.co/v1",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "meta-llama/Llama-3.1-8B-Instruct",
    envKey: "HUGGINGFACE_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true },
    docsUrl: "https://huggingface.co/docs/inference-providers/en/index",
    fallbackModels: models(["meta-llama/Llama-3.1-8B-Instruct", "Llama 3.1 8B"]),
  },
  {
    id: "azure_openai",
    name: "Azure OpenAI",
    category: "cloud",
    protocol: "azure-openai",
    baseURL: "",
    modelsEndpoint: "/openai/deployments?api-version=2025-06-01",
    chatEndpoint: "/openai/deployments/{model}/chat/completions?api-version=2025-06-01",
    defaultModel: "gpt-4o-mini",
    envKey: "AZURE_OPENAI_API_KEY",
    authType: "x-api-key",
    capabilities: { chat: true, models: false, vision: true, tools: true },
    docsUrl: "https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference",
    fallbackModels: models(["gpt-4o-mini", "Azure deployment"]),
    note: "Set base URL to your Azure OpenAI resource endpoint.",
  },
  {
    id: "vertex_ai",
    name: "Google Vertex AI",
    category: "cloud",
    protocol: "vertex-openai",
    baseURL: "",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "google/gemini-2.0-flash-001",
    envKey: "VERTEX_AI_ACCESS_TOKEN",
    authType: "bearer",
    capabilities: { chat: true, models: false, vision: true },
    docsUrl: "https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/call-vertex-using-openai-library",
    fallbackModels: models(["google/gemini-2.0-flash-001", "Gemini on Vertex"]),
    note: "Set base URL to the Vertex OpenAI-compatible endpoint for your project/location.",
  },
  {
    id: "bedrock",
    name: "Amazon Bedrock",
    category: "cloud",
    protocol: "bedrock-converse",
    baseURL: "",
    modelsEndpoint: "",
    chatEndpoint: "",
    defaultModel: "anthropic.claude-3-5-sonnet-20241022-v2:0",
    envKey: "AWS_ACCESS_KEY_ID",
    authType: "aws-sigv4",
    capabilities: { chat: true, models: false, tools: true },
    docsUrl: "https://docs.aws.amazon.com/bedrock/latest/userguide/conversation-inference.html",
    fallbackModels: models(["anthropic.claude-3-5-sonnet-20241022-v2:0", "Claude on Bedrock"]),
    note: "Requires AWS SigV4; first version validates configuration and routes through admin-visible custom setup.",
  },
  {
    id: "cohere",
    name: "Cohere",
    category: "global",
    protocol: "cohere",
    baseURL: "https://api.cohere.com",
    modelsEndpoint: "/v2/models",
    chatEndpoint: "/v2/chat",
    defaultModel: "command-a-plus-05-2026",
    envKey: "COHERE_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true, tools: true },
    docsUrl: "https://docs.cohere.com/reference/chat",
    fallbackModels: models(["command-a-plus-05-2026", "Command A+"], ["command-r-plus", "Command R+"]),
  },
  {
    id: "baidu_qianfan",
    name: "Baidu Qianfan",
    category: "china",
    protocol: "openai-compatible",
    baseURL: "https://api.baiduqianfan.ai/v1",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "ernie-4.0-turbo-8k",
    envKey: "BAIDU_QIANFAN_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true, vision: true, tools: true },
    docsUrl: "https://intl.cloud.baidu.com/doc/qianfan/index.html",
    fallbackModels: models(["ernie-4.0-turbo-8k", "ERNIE 4.0 Turbo"], ["deepseek-v3.1-250821", "DeepSeek V3.1"]),
  },
  {
    id: "tencent_hunyuan",
    name: "Tencent Hunyuan",
    category: "china",
    protocol: "openai-compatible",
    baseURL: "https://api.hunyuan.cloud.tencent.com/v1",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "hunyuan-turbo",
    envKey: "TENCENT_HUNYUAN_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true, tools: true },
    docsUrl: "https://cloud.tencent.com/document/product/1729/111007",
    fallbackModels: models(["hunyuan-turbo", "Hunyuan Turbo"]),
  },
  {
    id: "iflytek_spark",
    name: "iFlytek Spark",
    category: "china",
    protocol: "openai-compatible",
    baseURL: "https://spark-api-open.xf-yun.com/v1",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "4.0Ultra",
    envKey: "IFLYTEK_SPARK_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true },
    docsUrl: "https://www.xfyun.cn/doc/spark/HTTP%E8%B0%83%E7%94%A8%E6%96%87%E6%A1%A3.html",
    fallbackModels: models(["4.0Ultra", "Spark 4.0 Ultra"], ["generalv3.5", "Spark Max"]),
  },
  {
    id: "stepfun",
    name: "StepFun",
    category: "china",
    protocol: "openai-compatible",
    baseURL: "https://api.stepfun.ai/v1",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "step-2-mini",
    envKey: "STEPFUN_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true, vision: true },
    docsUrl: "https://platform.stepfun.ai/docs/en/api-reference/chat/chat-completion-create",
    fallbackModels: models(["step-2-mini", "Step 2 Mini"], ["step-1-8k", "Step 1 8K"]),
  },
  {
    id: "vllm",
    name: "vLLM",
    category: "local",
    protocol: "openai-compatible",
    baseURL: "http://localhost:8000/v1",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "local-model",
    envKey: "VLLM_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true, local: true, tools: true },
    docsUrl: "https://docs.vllm.ai/en/latest/serving/online_serving/openai_compatible_server/",
    fallbackModels: models(["local-model", "vLLM model"]),
  },
  {
    id: "lm_studio",
    name: "LM Studio",
    category: "local",
    protocol: "openai-compatible",
    baseURL: "http://localhost:1234/v1",
    modelsEndpoint: "/models",
    chatEndpoint: "/chat/completions",
    defaultModel: "local-model",
    envKey: "LM_STUDIO_API_KEY",
    authType: "bearer",
    capabilities: { chat: true, models: true, local: true, tools: true },
    docsUrl: "https://lmstudio.ai/docs/app/api",
    fallbackModels: models(["local-model", "LM Studio model"]),
  },
];

export const PROVIDER_MAP = Object.fromEntries(
  PROVIDER_DEFINITIONS.map((provider) => [provider.id, provider])
) as Record<string, ProviderDefinition>;

export function getProviderDefinition(provider: string) {
  return PROVIDER_MAP[provider] || null;
}

export function isSupportedProvider(provider: string) {
  return Boolean(getProviderDefinition(provider));
}

export function getProviderFallbackModels(provider: string) {
  return getProviderDefinition(provider)?.fallbackModels || [];
}
