"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import {
  AlertCircle,
  Check,
  Copy,
  ExternalLink,
  Eye,
  EyeOff,
  Github,
  Loader2,
  Save,
  Smartphone,
  TestTube,
  X,
} from "lucide-react";
import { toast } from "sonner";
import { ProfileForm } from "@/components/profile-form";
import { PageHeader } from "@/components/dashboard/page-header";
import { SectionPanel } from "@/components/layout/section-panel";
import { createClient } from "@/lib/supabase/client";
import { PROVIDER_DEFINITIONS } from "@/lib/ai/provider-registry";
import { MASKED_SECRET_PREFIX } from "@/lib/secrets/constants";
import { type DashboardLanguage, useDashboardLanguage } from "@/lib/dashboard-language";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

type TestState = "idle" | "testing" | "success" | "error";
type ModelOption = { id: string; label: string };

const firstProvider = PROVIDER_DEFINITIONS[0]?.id || "deepseek";
const DEFAULT_OLLAMA_BASE_URL = "http://localhost:11434";

const pageCopy = {
  zh: {
    saveFailed: "保存失败",
    settingsSaved: "设置已保存",
    generateFailed: "生成失败",
    extensionTokenGenerated: "扩展 Token 已生成",
    copied: "已复制",
    linkFailed: "绑定失败",
    testFailed: "测试失败",
    fetchModelsFailed: "获取模型失败",
    providerConnectionOk: "{name} 连接正常",
    modelsFetched: "已获取 {count} 个模型",
    ollamaConnectionOk: "Ollama 连接正常，发现 {count} 个模型",
    ollamaConnectionFailed: "Ollama 连接失败",
    pageTitle: "设置",
    pageSubtitle: "管理个人资料、扩展连接、GitHub 同步和个人 AI provider。",
    saveSettings: "保存设置",
    accountBindingsTitle: "账号绑定",
    accountBindingsDescription:
      "将 GitHub、Google 和邮箱登录绑定到当前账号，后续登录会进入同一份数据。",
    bindGithub: "绑定 GitHub",
    bindGoogle: "绑定 Google",
    embeddingModelTitle: "Embedding 模型",
    embeddingModelDescription:
      "语义搜索向量固定为 384 维；切换后新同步或重新生成的内容会使用新的 embedding 配置。",
    currentModelLabel: "当前模型",
    localXenovaTitle: "本地 Xenova",
    localXenovaDescription: "默认使用 Xenova/all-MiniLM-L6-v2，不消耗 OpenAI API。",
    openaiEmbeddingsTitle: "OpenAI Embeddings",
    openaiEmbeddingsDescription:
      "使用 OPENAI_EMBEDDING_MODEL，默认 text-embedding-3-small，输出 384 维。",
    extensionConnectionTitle: "扩展连接",
    extensionConnectionDescription:
      "推荐从扩展点击登录自动连接；这里仍保留手动 Token 作为备用方式。",
    currentBackupToken: "当前备用 Token: {value}",
    regenerateBackupToken: "重新生成备用 Token",
    generateBackupToken: "生成备用 Token",
    personalProviderTitle: "个人 AI Provider",
    personalProviderDescription:
      "选择一个 provider 后展开配置；模型列表优先从 provider API 拉取，失败时显示内置兜底模型。",
    providerLabel: "Provider",
    setAsDefault: "设为默认",
    defaultBadge: "默认",
    configuredStatus: "已配置 ({source})",
    notConfiguredStatus: "未配置个人 Key，可使用环境变量或在下方填写",
    docsLink: "文档",
    ollamaLocalAddressLabel: "Ollama 本地地址",
    ollamaHelper:
      "默认端口为 11434。Vercel 云端无法访问你电脑上的 localhost，检测会从当前浏览器直接访问本机 Ollama。",
    detectOllama: "检测 Ollama",
    apiKeyLabel: "API Key",
    noKeyNeededPlaceholder: "无需 Key",
    defaultModelLabel: "默认模型",
    useProviderDefaultOption: "使用 provider 默认: {model}",
    fetchModels: "获取模型",
    testConnection: "测试连接",
    availableModelsLabel: "可用模型 ({count})",
    githubStarsTitle: "GitHub Stars",
    githubStarsDescription:
      "使用 GitHub 登录时可直接同步；用户名用于未通过 GitHub 登录时的公开 Stars 同步。",
    githubUsernameLabel: "GitHub 用户名",
    authorizeWithGithub: "使用 GitHub 登录授权",
    githubServerCredentials: "服务端已配置 GitHub 备用凭据",
    githubAuthFromAccount: "GitHub 授权将由当前登录账号提供",
    githubBindFirst: "请先绑定 GitHub 账号以启用私有授权能力",
    automationTitle: "自动化偏好",
    autoGenerateDescription: "同步时自动生成 AI 描述",
    autoSnapshot: "同步后保存快照",
    aiDescriptionPromptTitle: "AI 描述提示词",
    aiDescriptionPromptHelp: "留空时使用内置结构化 JSON 模板。",
    aiDescriptionPromptPlaceholder:
      "自定义 AI 生成描述时使用的 system prompt，需要求模型返回 purpose/content/audience JSON。",
  },
  en: {
    saveFailed: "Save failed",
    settingsSaved: "Settings saved",
    generateFailed: "Generation failed",
    extensionTokenGenerated: "Extension token generated",
    copied: "Copied",
    linkFailed: "Linking failed",
    testFailed: "Test failed",
    fetchModelsFailed: "Failed to fetch models",
    providerConnectionOk: "{name} connection OK",
    modelsFetched: "Fetched {count} models",
    ollamaConnectionOk: "Ollama connection OK, found {count} models",
    ollamaConnectionFailed: "Ollama connection failed",
    pageTitle: "Settings",
    pageSubtitle: "Manage your profile, extension connection, GitHub sync, and personal AI provider.",
    saveSettings: "Save settings",
    accountBindingsTitle: "Account linking",
    accountBindingsDescription:
      "Link GitHub, Google, and email sign-in to the current account so future logins share the same data.",
    bindGithub: "Link GitHub",
    bindGoogle: "Link Google",
    embeddingModelTitle: "Embedding model",
    embeddingModelDescription:
      "Semantic search vectors are fixed at 384 dimensions; newly synced or regenerated content will use the new embedding configuration after switching.",
    currentModelLabel: "Current model",
    localXenovaTitle: "Local Xenova",
    localXenovaDescription: "Uses Xenova/all-MiniLM-L6-v2 by default, no OpenAI API usage.",
    openaiEmbeddingsTitle: "OpenAI Embeddings",
    openaiEmbeddingsDescription:
      "Uses OPENAI_EMBEDDING_MODEL, defaults to text-embedding-3-small, outputs 384 dimensions.",
    extensionConnectionTitle: "Extension connection",
    extensionConnectionDescription:
      "Sign in from the extension to auto-connect; a manual token remains available here as a fallback.",
    currentBackupToken: "Current backup token: {value}",
    regenerateBackupToken: "Regenerate backup token",
    generateBackupToken: "Generate backup token",
    personalProviderTitle: "Personal AI provider",
    personalProviderDescription:
      "Select a provider to expand its configuration; the model list is fetched from the provider API first, with built-in fallback models shown on failure.",
    providerLabel: "Provider",
    setAsDefault: "Set as default",
    defaultBadge: "Default",
    configuredStatus: "Configured ({source})",
    notConfiguredStatus: "No personal key configured; use environment variables or fill in below",
    docsLink: "Docs",
    ollamaLocalAddressLabel: "Ollama local address",
    ollamaHelper:
      "Default port is 11434. Vercel cloud cannot reach localhost on your machine; the check accesses your local Ollama directly from this browser.",
    detectOllama: "Detect Ollama",
    apiKeyLabel: "API key",
    noKeyNeededPlaceholder: "No key required",
    defaultModelLabel: "Default model",
    useProviderDefaultOption: "Use provider default: {model}",
    fetchModels: "Fetch models",
    testConnection: "Test connection",
    availableModelsLabel: "Available models ({count})",
    githubStarsTitle: "GitHub Stars",
    githubStarsDescription:
      "Sign in with GitHub to sync directly; the username is used for public Stars sync when not signed in with GitHub.",
    githubUsernameLabel: "GitHub username",
    authorizeWithGithub: "Authorize with GitHub",
    githubServerCredentials: "Server has GitHub backup credentials configured",
    githubAuthFromAccount: "GitHub authorization will be provided by the current signed-in account",
    githubBindFirst: "Please link a GitHub account first to enable private authorization",
    automationTitle: "Automation preferences",
    autoGenerateDescription: "Auto-generate AI descriptions on sync",
    autoSnapshot: "Save snapshot after sync",
    aiDescriptionPromptTitle: "AI description prompt",
    aiDescriptionPromptHelp: "Leave blank to use the built-in structured JSON template.",
    aiDescriptionPromptPlaceholder:
      "Custom system prompt for AI descriptions. It should ask the model to return purpose/content/audience JSON.",
  },
} as const;

function isMaskedSecret(value: string | undefined) {
  return Boolean(value && value.startsWith(MASKED_SECRET_PREFIX));
}

export default function SettingsPage() {
  const [language] = useDashboardLanguage();
  const t = pageCopy[language];
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [selectedProvider, setSelectedProvider] = useState(firstProvider);
  const providerSelector = selectedProvider;
  const [defaultProvider, setDefaultProvider] = useState("deepseek");
  const [defaultModel, setDefaultModel] = useState("");
  const [apiKeys, setApiKeys] = useState<Record<string, string>>({});
  const [showKeys, setShowKeys] = useState<Record<string, boolean>>({});
  const [providerStatus, setProviderStatus] = useState<
    Record<string, { configured: boolean; source: string }>
  >({});
  const [testStates, setTestStates] = useState<Record<string, TestState>>({});
  const [testErrors, setTestErrors] = useState<Record<string, string>>({});
  const [testLatencies, setTestLatencies] = useState<Record<string, number>>({});
  const [modelStates, setModelStates] = useState<Record<string, TestState>>({});
  const [modelErrors, setModelErrors] = useState<Record<string, string>>({});
  const [providerModels, setProviderModels] = useState<Record<string, ModelOption[]>>({});

  const [githubUsername, setGithubUsername] = useState("");
  const [githubStatus, setGithubStatus] = useState({
    configured: false,
    hasEnvToken: false,
  });
  const [autoDescription, setAutoDescription] = useState(false);
  const [autoSnapshot, setAutoSnapshot] = useState(false);
  const [aiDescriptionPrompt, setAiDescriptionPrompt] = useState("");
  const [embeddingPreference, setEmbeddingPreference] = useState<"local" | "openai">("local");
  const [embeddingModel, setEmbeddingModel] = useState("Xenova/all-MiniLM-L6-v2");

  const [extensionTokenPreview, setExtensionTokenPreview] = useState<string | null>(null);
  const [extensionTokenGenerated, setExtensionTokenGenerated] = useState<string | null>(null);
  const [extensionTokenLoading, setExtensionTokenLoading] = useState(false);

  const selectedDefinition = useMemo(
    () =>
      PROVIDER_DEFINITIONS.find((provider) => provider.id === providerSelector) ||
      PROVIDER_DEFINITIONS[0],
    [providerSelector]
  );
  const selectedIsOllama = selectedDefinition?.id === "ollama";
  const [ollamaBaseUrl, setOllamaBaseUrl] = useState(DEFAULT_OLLAMA_BASE_URL);

  const selectedModels =
    providerModels[selectedProvider] || selectedDefinition?.fallbackModels || [];
  const selectedStatus = providerStatus[selectedProvider];
  const selectedTestState = testStates[selectedProvider] || "idle";
  const selectedModelState = modelStates[selectedProvider] || "idle";

  const loadExtensionTokenStatus = useCallback(async () => {
    try {
      const res = await fetch("/api/settings/extension-token");
      if (res.ok) {
        const data = await res.json();
        setExtensionTokenPreview(data.hasToken ? data.tokenPreview : null);
      }
    } catch (error) {
      console.error("Failed to load extension token status:", error);
    }
  }, []);

  const loadSettings = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/settings");
      if (res.ok) {
        const data = await res.json();
        setDefaultProvider(data.defaultProvider || "deepseek");
        setDefaultModel(data.defaultModel || "");
        setSelectedProvider(data.defaultProvider || firstProvider);
        setProviderStatus(data.providers || {});
        setApiKeys(data.userApiKeys || {});
        setProviderModels(data.providerModels || {});
        setGithubUsername(data.github?.username || "");
        setGithubStatus({
          configured: data.github?.configured || false,
          hasEnvToken: data.github?.hasEnvToken || false,
        });
        setAutoDescription(data.autoGenerateDescription || false);
        setAutoSnapshot(data.autoSnapshot || false);
        setAiDescriptionPrompt(data.aiDescriptionPrompt || "");
        setEmbeddingPreference(data.embeddingPreference === "openai" ? "openai" : "local");
        setEmbeddingModel(data.embeddingModel || "Xenova/all-MiniLM-L6-v2");
        await loadExtensionTokenStatus();
      }
    } catch (error) {
      console.error("Failed to load settings:", error);
    } finally {
      setLoading(false);
    }
  }, [loadExtensionTokenStatus]);

  useEffect(() => {
    loadSettings();
    setOllamaBaseUrl(
      window.localStorage.getItem("smart-favorites:ollama-base-url") ||
        DEFAULT_OLLAMA_BASE_URL
    );
  }, [loadSettings]);

  const handleSave = async () => {
    setSaving(true);
    try {
      const keysToSend: Record<string, string | null> = {};
      for (const [key, value] of Object.entries(apiKeys)) {
        if (value && !isMaskedSecret(value)) {
          keysToSend[key] = value;
        }
      }

      const res = await fetch("/api/settings", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          default_llm_provider: selectedProvider,
          default_llm_model: defaultModel || undefined,
          api_keys: keysToSend,
          github_username: githubUsername,
          embedding_preference: embeddingPreference,
          auto_generate_description: autoDescription,
          auto_snapshot: autoSnapshot,
          ai_description_prompt: aiDescriptionPrompt,
        }),
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || t.saveFailed);
      }

      toast.success(t.settingsSaved);
      await loadSettings();
    } catch (error: any) {
      toast.error(error.message || t.saveFailed);
    } finally {
      setSaving(false);
    }
  };

  const handleGenerateExtensionToken = async () => {
    setExtensionTokenLoading(true);
    try {
      const res = await fetch("/api/settings/extension-token", { method: "POST" });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || t.generateFailed);
      setExtensionTokenGenerated(data.token);
      setExtensionTokenPreview(data.token ? `${MASKED_SECRET_PREFIX}${data.token.slice(-8)}` : null);
      toast.success(t.extensionTokenGenerated);
    } catch (error: any) {
      toast.error(error.message || t.generateFailed);
    } finally {
      setExtensionTokenLoading(false);
    }
  };

  const copyExtensionToken = async () => {
    if (!extensionTokenGenerated) return;
    await navigator.clipboard.writeText(extensionTokenGenerated);
    toast.success(t.copied);
  };

  const linkIdentity = async (provider: "github" | "google") => {
    const supabase = createClient();
    const { error } = await supabase.auth.linkIdentity({
      provider,
      options: {
        redirectTo: `${window.location.origin}/dashboard/settings`,
        scopes: provider === "github" ? "read:user user:email" : undefined,
      },
    });

    if (error) {
      toast.error(error.message || t.linkFailed);
    }
  };

  const testProvider = async (provider: string) => {
    setTestStates((current) => ({ ...current, [provider]: "testing" }));
    setTestErrors((current) => ({ ...current, [provider]: "" }));
    try {
      const key = apiKeys[provider];
      const body: Record<string, string> = { provider };
      if (key && !isMaskedSecret(key)) body.apiKey = key;
      if (defaultModel) body.model = defaultModel;

      const res = await fetch("/api/settings/test", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      const data = await res.json();
      if (!data.success) throw new Error(data.error || t.testFailed);

      setTestStates((current) => ({ ...current, [provider]: "success" }));
      setTestLatencies((current) => ({ ...current, [provider]: data.latency || 0 }));
      toast.success(t.providerConnectionOk.replace("{name}", selectedDefinition?.name || provider));
    } catch (error: any) {
      setTestStates((current) => ({ ...current, [provider]: "error" }));
      setTestErrors((current) => ({ ...current, [provider]: error.message || t.testFailed }));
    }
  };

  const loadProviderModels = async (provider: string) => {
    setModelStates((current) => ({ ...current, [provider]: "testing" }));
    setModelErrors((current) => ({ ...current, [provider]: "" }));
    try {
      const key = apiKeys[provider];
      const body: Record<string, string> = { provider };
      if (key && !isMaskedSecret(key)) body.apiKey = key;

      const res = await fetch("/api/settings/models", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      const data = await res.json();
      if (!data.success) throw new Error(data.error || t.fetchModelsFailed);

      setProviderModels((current) => ({ ...current, [provider]: data.models || [] }));
      setModelStates((current) => ({ ...current, [provider]: "success" }));
      toast.success(t.modelsFetched.replace("{count}", String(data.models?.length || 0)));
    } catch (error: any) {
      setModelStates((current) => ({ ...current, [provider]: "error" }));
      setModelErrors((current) => ({ ...current, [provider]: error.message || t.fetchModelsFailed }));
    }
  };

  const testLocalOllama = async () => {
    setModelStates((current) => ({ ...current, ollama: "testing" }));
    setModelErrors((current) => ({ ...current, ollama: "" }));
    const baseUrl = ollamaBaseUrl.trim().replace(/\/$/, "") || DEFAULT_OLLAMA_BASE_URL;
    window.localStorage.setItem("smart-favorites:ollama-base-url", baseUrl);

    try {
      const res = await fetch(`${baseUrl}/api/tags`, {
        signal: AbortSignal.timeout(5000),
      });
      if (!res.ok) throw new Error(`Ollama responded ${res.status}`);
      const data = await res.json();
      const models = (data.models || []).map((item: any) => ({
        id: item.name,
        label: item.name,
      }));
      setProviderModels((current) => ({ ...current, ollama: models }));
      setModelStates((current) => ({ ...current, ollama: "success" }));
      toast.success(t.ollamaConnectionOk.replace("{count}", String(models.length)));
    } catch (error: any) {
      setModelStates((current) => ({ ...current, ollama: "error" }));
      setModelErrors((current) => ({
        ...current,
        ollama: error.message || t.ollamaConnectionFailed,
      }));
    }
  };

  if (loading) {
    return <div className="h-48 animate-pulse rounded-lg bg-muted" />;
  }

  return (
    <div className="page-stack max-w-5xl">
      <PageHeader
        title={t.pageTitle}
        description={t.pageSubtitle}
        actions={
          <Button variant="creative" onClick={handleSave} disabled={saving}>
            {saving ? (
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            ) : (
              <Save className="mr-2 h-4 w-4" />
            )}
            {t.saveSettings}
          </Button>
        }
      />

      <ProfileForm />

      <SectionPanel
        title={t.accountBindingsTitle}
        description={t.accountBindingsDescription}
      >
        <div className="flex flex-wrap gap-2">
          <Button variant="outline" onClick={() => linkIdentity("github")}>
            <Github className="mr-2 h-4 w-4" />
            {t.bindGithub}
          </Button>
          <Button variant="outline" onClick={() => linkIdentity("google")}>
            {t.bindGoogle}
          </Button>
        </div>
      </SectionPanel>

      <SectionPanel
        title={t.embeddingModelTitle}
        description={t.embeddingModelDescription}
      >
        <div className="grid gap-3 md:grid-cols-2">
          <div className="space-y-1.5">
            <Label>{t.currentModelLabel}</Label>
            <Input readOnly value={embeddingModel} className="h-9" />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="embedding-preference">{t.embeddingModelTitle}</Label>
            <select
              id="embedding-preference"
              value={embeddingPreference}
              onChange={(event) =>
                setEmbeddingPreference(event.target.value === "openai" ? "openai" : "local")
              }
              className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm"
            >
              <option value="local">{t.localXenovaTitle}</option>
              <option value="openai">{t.openaiEmbeddingsTitle}</option>
            </select>
          </div>
        </div>
      </SectionPanel>

      <SectionPanel
        title={
          <span className="inline-flex items-center gap-2">
            <Smartphone className="h-5 w-5" />
            {t.extensionConnectionTitle}
          </span>
        }
        description={t.extensionConnectionDescription}
      >
        <div className="space-y-3">
          {extensionTokenGenerated ? (
            <div className="flex gap-2">
              <Input readOnly value={extensionTokenGenerated} className="font-mono text-sm" />
              <Button variant="outline" size="icon" onClick={copyExtensionToken}>
                <Copy className="h-4 w-4" />
              </Button>
            </div>
          ) : (
            <div className="flex flex-wrap items-center gap-3">
              {extensionTokenPreview && (
                <span className="text-sm text-muted-foreground">{t.currentBackupToken.replace("{value}", extensionTokenPreview)}</span>
              )}
              <Button variant="outline" onClick={handleGenerateExtensionToken} disabled={extensionTokenLoading}>
                {extensionTokenLoading ? (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                ) : (
                  <Smartphone className="mr-2 h-4 w-4" />
                )}
                {extensionTokenPreview ? t.regenerateBackupToken : t.generateBackupToken}
              </Button>
            </div>
          )}
        </div>
      </SectionPanel>

      <SectionPanel
        title={t.personalProviderTitle}
        description={t.personalProviderDescription}
      >
        <div className="space-y-4">
          <div className="grid gap-3 md:grid-cols-[minmax(0,1fr)_auto]">
            <div className="space-y-1.5">
              <Label htmlFor="provider-select">{t.providerLabel}</Label>
              <select
                id="provider-select"
                value={selectedProvider}
                onChange={(event) => {
                  setSelectedProvider(event.target.value);
                  setDefaultProvider(event.target.value);
                  setDefaultModel("");
                }}
                className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm"
              >
                {PROVIDER_DEFINITIONS.map((provider) => (
                  <option key={provider.id} value={provider.id}>
                    {provider.name} ({provider.category})
                  </option>
                ))}
              </select>
            </div>
            <div className="flex items-end">
              <Button variant="outline" onClick={() => setDefaultProvider(selectedProvider)}>
                {t.setAsDefault}
              </Button>
            </div>
          </div>

          {selectedDefinition && (
            <div className="rounded-lg border p-3">
              <div className="flex flex-wrap items-center justify-between gap-3">
                <div>
                  <div className="flex items-center gap-2">
                    <h3 className="font-semibold">{selectedDefinition.name}</h3>
                    <Badge variant="secondary">{selectedDefinition.protocol}</Badge>
                    {defaultProvider === selectedProvider && <Badge>{t.defaultBadge}</Badge>}
                  </div>
                  <p className="mt-1 text-sm text-muted-foreground">
                    {selectedStatus?.configured
                      ? t.configuredStatus.replace("{source}", selectedStatus.source)
                      : t.notConfiguredStatus}
                  </p>
                </div>
                <a
                  href={selectedDefinition.docsUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-1 text-sm text-primary hover:underline"
                >
                  {t.docsLink}
                  <ExternalLink className="h-3.5 w-3.5" />
                </a>
              </div>

              <div className="mt-3 grid gap-3 md:grid-cols-2">
                {selectedIsOllama ? (
                  <div className="space-y-1.5">
                    <Label>{t.ollamaLocalAddressLabel}</Label>
                    <div className="rounded-md border bg-muted/30 p-3">
                      <Input
                        value={ollamaBaseUrl}
                        onChange={(event) => setOllamaBaseUrl(event.target.value)}
                        placeholder={DEFAULT_OLLAMA_BASE_URL}
                      />
                      <p className="mt-2 text-xs text-muted-foreground">
                        {t.ollamaHelper}
                      </p>
                      <Button type="button" variant="outline" className="mt-3" onClick={testLocalOllama}>
                        <TestTube className="mr-2 h-4 w-4" />
                        {t.detectOllama}
                      </Button>
                    </div>
                  </div>
                ) : (
                  <div className="space-y-1.5">
                    <Label>{t.apiKeyLabel}</Label>
                    <div className="relative">
                      <Input
                        type={showKeys[selectedProvider] ? "text" : "password"}
                        placeholder={selectedDefinition.authType === "none" ? t.noKeyNeededPlaceholder : "sk-..."}
                        value={apiKeys[selectedProvider] || ""}
                        onChange={(event) =>
                          setApiKeys((current) => ({
                            ...current,
                            [selectedProvider]: event.target.value,
                          }))
                        }
                        className="pr-10"
                      />
                      <button
                        type="button"
                        onClick={() =>
                          setShowKeys((current) => ({
                            ...current,
                            [selectedProvider]: !current[selectedProvider],
                          }))
                        }
                        className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground"
                      >
                        {showKeys[selectedProvider] ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                      </button>
                    </div>
                  </div>
                )}

                <div className="space-y-1.5">
                  <Label>{t.defaultModelLabel}</Label>
                  <select
                    value={defaultModel}
                    onChange={(event) => setDefaultModel(event.target.value)}
                    className="h-9 w-full rounded-md border border-input bg-background px-3 text-sm"
                  >
                    <option value="">{t.useProviderDefaultOption.replace("{model}", selectedDefinition.defaultModel)}</option>
                    {selectedModels.map((model) => (
                      <option key={model.id} value={model.id}>
                        {model.label || model.id}
                      </option>
                    ))}
                  </select>
                </div>
              </div>

              {selectedDefinition.note && (
                <p className="mt-3 text-xs text-muted-foreground">{selectedDefinition.note}</p>
              )}

              <div className="mt-4 flex flex-wrap gap-2">
                <Button
                  variant="outline"
                  onClick={() => selectedIsOllama ? testLocalOllama() : loadProviderModels(selectedProvider)}
                  disabled={selectedModelState === "testing"}
                >
                  {selectedModelState === "testing" ? (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  ) : selectedModelState === "success" ? (
                    <Check className="mr-2 h-4 w-4 text-green-600" />
                  ) : selectedModelState === "error" ? (
                    <X className="mr-2 h-4 w-4 text-red-600" />
                  ) : (
                    <TestTube className="mr-2 h-4 w-4" />
                  )}
                  {t.fetchModels}
                </Button>
                <Button
                  variant="outline"
                  onClick={() => selectedIsOllama ? testLocalOllama() : testProvider(selectedProvider)}
                  disabled={selectedTestState === "testing"}
                >
                  {selectedTestState === "testing" ? (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  ) : selectedTestState === "success" ? (
                    <Check className="mr-2 h-4 w-4 text-green-600" />
                  ) : selectedTestState === "error" ? (
                    <X className="mr-2 h-4 w-4 text-red-600" />
                  ) : (
                    <TestTube className="mr-2 h-4 w-4" />
                  )}
                  {t.testConnection}
                  {testLatencies[selectedProvider] ? (
                    <span className="ml-2 text-xs">{testLatencies[selectedProvider]}ms</span>
                  ) : null}
                </Button>
              </div>

              {selectedModels.length > 0 && (
                <div className="mt-4 rounded-md border bg-muted/30 p-3">
                  <p className="mb-2 text-xs font-medium text-muted-foreground">
                    {t.availableModelsLabel.replace("{count}", String(selectedModels.length))}
                  </p>
                  <div className="flex max-h-28 flex-wrap gap-1 overflow-y-auto">
                    {selectedModels.slice(0, 40).map((model) => (
                      <Badge key={model.id} variant="secondary" className="text-[10px]">
                        {model.label || model.id}
                      </Badge>
                    ))}
                  </div>
                </div>
              )}

              {(testErrors[selectedProvider] || modelErrors[selectedProvider]) && (
                <div className="mt-4 flex items-start gap-2 rounded bg-red-50 p-2 text-xs text-red-700">
                  <AlertCircle className="mt-0.5 h-3.5 w-3.5 shrink-0" />
                  <span>{testErrors[selectedProvider] || modelErrors[selectedProvider]}</span>
                </div>
              )}
            </div>
          )}
        </div>
      </SectionPanel>

      <SectionPanel
        title={
          <span className="inline-flex items-center gap-2">
            <Github className="h-5 w-5" />
            {t.githubStarsTitle}
          </span>
        }
        description={t.githubStarsDescription}
      >
        <div className="space-y-3">
          <div className="space-y-1.5">
            <Label>{t.githubUsernameLabel}</Label>
            <Input
              placeholder="your-username"
              value={githubUsername}
              onChange={(event) => setGithubUsername(event.target.value)}
            />
          </div>
          <div className="flex flex-wrap items-center gap-3 rounded-lg border p-3">
            <Button variant="outline" onClick={() => linkIdentity("github")}>
              <Github className="mr-2 h-4 w-4" />
              {t.authorizeWithGithub}
            </Button>
            <span className="text-sm text-muted-foreground">
              {githubStatus.configured
                ? githubStatus.hasEnvToken
                  ? t.githubServerCredentials
                  : t.githubAuthFromAccount
                : t.githubBindFirst}
            </span>
          </div>
        </div>
      </SectionPanel>

      <SectionPanel title={t.automationTitle}>
        <div className="space-y-3">
          <div className="grid gap-2 md:grid-cols-2">
            <label className="flex items-center justify-between rounded-md border px-3 py-2 text-sm">
              <span>{t.autoGenerateDescription}</span>
              <input
                type="checkbox"
                checked={autoDescription}
                onChange={(event) => setAutoDescription(event.target.checked)}
              />
            </label>
            <label className="flex items-center justify-between rounded-md border px-3 py-2 text-sm">
              <span>{t.autoSnapshot}</span>
              <input
                type="checkbox"
                checked={autoSnapshot}
                onChange={(event) => setAutoSnapshot(event.target.checked)}
              />
            </label>
          </div>
          <div className="space-y-1.5">
            <div className="flex items-center justify-between gap-3">
              <Label htmlFor="ai-description-prompt">{t.aiDescriptionPromptTitle}</Label>
              <span className="text-xs text-muted-foreground">{t.aiDescriptionPromptHelp}</span>
            </div>
            <textarea
              id="ai-description-prompt"
              value={aiDescriptionPrompt}
              onChange={(event) => setAiDescriptionPrompt(event.target.value)}
              placeholder={t.aiDescriptionPromptPlaceholder}
              className="min-h-28 w-full rounded-md border border-input bg-background px-3 py-2 text-sm leading-5 shadow-sm focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
            />
          </div>
        </div>
      </SectionPanel>
    </div>
  );
}
