"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import {
  AlertCircle,
  Check,
  Copy,
  ExternalLink,
  Eye,
  EyeOff,
  Github,
  Loader2,
  Save,
  Smartphone,
  TestTube,
  X,
} from "lucide-react";
import { toast } from "sonner";
import { ProfileForm } from "@/components/profile-form";
import { createClient } from "@/lib/supabase/client";
import { PROVIDER_DEFINITIONS } from "@/lib/ai/provider-registry";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

type TestState = "idle" | "testing" | "success" | "error";
type ModelOption = { id: string; label: string };

const firstProvider = PROVIDER_DEFINITIONS[0]?.id || "deepseek";

export default function SettingsPage() {
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [selectedProvider, setSelectedProvider] = useState(firstProvider);
  const providerSelector = selectedProvider;
  const [defaultProvider, setDefaultProvider] = useState("deepseek");
  const [defaultModel, setDefaultModel] = useState("");
  const [apiKeys, setApiKeys] = useState<Record<string, string>>({});
  const [showKeys, setShowKeys] = useState<Record<string, boolean>>({});
  const [providerStatus, setProviderStatus] = useState<
    Record<string, { configured: boolean; source: string }>
  >({});
  const [testStates, setTestStates] = useState<Record<string, TestState>>({});
  const [testErrors, setTestErrors] = useState<Record<string, string>>({});
  const [testLatencies, setTestLatencies] = useState<Record<string, number>>({});
  const [modelStates, setModelStates] = useState<Record<string, TestState>>({});
  const [modelErrors, setModelErrors] = useState<Record<string, string>>({});
  const [providerModels, setProviderModels] = useState<Record<string, ModelOption[]>>({});

  const [githubUsername, setGithubUsername] = useState("");
  const [githubStatus, setGithubStatus] = useState({
    configured: false,
    hasEnvToken: false,
  });
  const [autoDescription, setAutoDescription] = useState(false);
  const [autoSnapshot, setAutoSnapshot] = useState(false);

  const [extensionTokenPreview, setExtensionTokenPreview] = useState<string | null>(null);
  const [extensionTokenGenerated, setExtensionTokenGenerated] = useState<string | null>(null);
  const [extensionTokenLoading, setExtensionTokenLoading] = useState(false);

  const selectedDefinition = useMemo(
    () =>
      PROVIDER_DEFINITIONS.find((provider) => provider.id === providerSelector) ||
      PROVIDER_DEFINITIONS[0],
    [providerSelector]
  );
  const selectedRequiresGitHubLogin = selectedDefinition?.authType === "github-oauth";

  const selectedModels =
    providerModels[selectedProvider] || selectedDefinition?.fallbackModels || [];
  const selectedStatus = providerStatus[selectedProvider];
  const selectedTestState = testStates[selectedProvider] || "idle";
  const selectedModelState = modelStates[selectedProvider] || "idle";

  const loadExtensionTokenStatus = useCallback(async () => {
    try {
      const res = await fetch("/api/settings/extension-token");
      if (res.ok) {
        const data = await res.json();
        setExtensionTokenPreview(data.hasToken ? data.tokenPreview : null);
      }
    } catch (error) {
      console.error("Failed to load extension token status:", error);
    }
  }, []);

  const loadSettings = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/settings");
      if (res.ok) {
        const data = await res.json();
        setDefaultProvider(data.defaultProvider || "deepseek");
        setSelectedProvider(data.defaultProvider || firstProvider);
        setProviderStatus(data.providers || {});
        setApiKeys(data.userApiKeys || {});
        setGithubUsername(data.github?.username || "");
        setGithubStatus({
          configured: data.github?.configured || false,
          hasEnvToken: data.github?.hasEnvToken || false,
        });
        setAutoDescription(data.autoGenerateDescription || false);
        setAutoSnapshot(data.autoSnapshot || false);
        await loadExtensionTokenStatus();
      }
    } catch (error) {
      console.error("Failed to load settings:", error);
    } finally {
      setLoading(false);
    }
  }, [loadExtensionTokenStatus]);

  useEffect(() => {
    loadSettings();
  }, [loadSettings]);

  const handleSave = async () => {
    setSaving(true);
    try {
      const keysToSend: Record<string, string | null> = {};
      for (const [key, value] of Object.entries(apiKeys)) {
        if (value && !value.startsWith("••••")) {
          keysToSend[key] = value;
        }
      }

      const res = await fetch("/api/settings", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          default_llm_provider: defaultProvider,
          default_llm_model: defaultModel || undefined,
          api_keys: keysToSend,
          github_username: githubUsername,
          auto_generate_description: autoDescription,
          auto_snapshot: autoSnapshot,
        }),
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || "保存失败");
      }

      toast.success("设置已保存");
      await loadSettings();
    } catch (error: any) {
      toast.error(error.message || "保存失败");
    } finally {
      setSaving(false);
    }
  };

  const handleGenerateExtensionToken = async () => {
    setExtensionTokenLoading(true);
    try {
      const res = await fetch("/api/settings/extension-token", { method: "POST" });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "生成失败");
      setExtensionTokenGenerated(data.token);
      setExtensionTokenPreview(data.token ? `••••${data.token.slice(-8)}` : null);
      toast.success("扩展 Token 已生成");
    } catch (error: any) {
      toast.error(error.message || "生成失败");
    } finally {
      setExtensionTokenLoading(false);
    }
  };

  const copyExtensionToken = async () => {
    if (!extensionTokenGenerated) return;
    await navigator.clipboard.writeText(extensionTokenGenerated);
    toast.success("已复制");
  };

  const linkIdentity = async (provider: "github" | "google") => {
    const supabase = createClient();
    const { error } = await supabase.auth.linkIdentity({
      provider,
      options: {
        redirectTo: `${window.location.origin}/dashboard/settings`,
        scopes: provider === "github" ? "read:user user:email" : undefined,
      },
    });

    if (error) {
      toast.error(error.message || "绑定失败");
    }
  };

  const loginWithGitHub = () => {
    const loginUrl = new URL("/auth/sign-in/github", window.location.origin);
    loginUrl.searchParams.set("redirect", "/dashboard/settings");
    window.location.href = loginUrl.toString();
  };

  const testProvider = async (provider: string) => {
    setTestStates((current) => ({ ...current, [provider]: "testing" }));
    setTestErrors((current) => ({ ...current, [provider]: "" }));
    try {
      const key = apiKeys[provider];
      const body: Record<string, string> = { provider };
      if (key && !key.startsWith("••••")) body.apiKey = key;
      if (defaultModel) body.model = defaultModel;

      const res = await fetch("/api/settings/test", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      const data = await res.json();
      if (!data.success) throw new Error(data.error || "测试失败");

      setTestStates((current) => ({ ...current, [provider]: "success" }));
      setTestLatencies((current) => ({ ...current, [provider]: data.latency || 0 }));
      toast.success(`${selectedDefinition?.name || provider} 连接正常`);
    } catch (error: any) {
      setTestStates((current) => ({ ...current, [provider]: "error" }));
      setTestErrors((current) => ({ ...current, [provider]: error.message || "测试失败" }));
    }
  };

  const loadProviderModels = async (provider: string) => {
    setModelStates((current) => ({ ...current, [provider]: "testing" }));
    setModelErrors((current) => ({ ...current, [provider]: "" }));
    try {
      const key = apiKeys[provider];
      const body: Record<string, string> = { provider };
      if (key && !key.startsWith("••••")) body.apiKey = key;

      const res = await fetch("/api/settings/models", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      const data = await res.json();
      if (!data.success) throw new Error(data.error || "获取模型失败");

      setProviderModels((current) => ({ ...current, [provider]: data.models || [] }));
      setModelStates((current) => ({ ...current, [provider]: "success" }));
      toast.success(`已获取 ${data.models?.length || 0} 个模型`);
    } catch (error: any) {
      setModelStates((current) => ({ ...current, [provider]: "error" }));
      setModelErrors((current) => ({ ...current, [provider]: error.message || "获取模型失败" }));
    }
  };

  if (loading) {
    return <div className="h-48 animate-pulse rounded-lg bg-muted" />;
  }

  return (
    <div className="max-w-4xl space-y-6">
      <div className="flex items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">设置</h1>
          <p className="mt-1 text-muted-foreground">
            管理个人资料、扩展连接、GitHub 同步和个人 AI provider。
          </p>
        </div>
        <Button onClick={handleSave} disabled={saving}>
          {saving ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Save className="mr-2 h-4 w-4" />}
          保存设置
        </Button>
      </div>

      <ProfileForm />

      <Card>
        <CardHeader>
          <CardTitle>账号绑定</CardTitle>
          <CardDescription>
            将 GitHub、Google 和邮箱登录绑定到当前账号，后续登录会进入同一份数据。
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-wrap gap-2">
          <Button variant="outline" onClick={() => linkIdentity("github")}>
            <Github className="mr-2 h-4 w-4" />
            绑定 GitHub
          </Button>
          <Button variant="outline" onClick={() => linkIdentity("google")}>
            绑定 Google
          </Button>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Smartphone className="h-5 w-5" />
            扩展连接
          </CardTitle>
          <CardDescription>
            推荐从扩展点击登录自动连接；这里仍保留手动 Token 作为备用方式。
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          {extensionTokenGenerated ? (
            <div className="flex gap-2">
              <Input readOnly value={extensionTokenGenerated} className="font-mono text-sm" />
              <Button variant="outline" size="icon" onClick={copyExtensionToken}>
                <Copy className="h-4 w-4" />
              </Button>
            </div>
          ) : (
            <div className="flex flex-wrap items-center gap-3">
              {extensionTokenPreview && (
                <span className="text-sm text-muted-foreground">当前备用 Token: {extensionTokenPreview}</span>
              )}
              <Button variant="outline" onClick={handleGenerateExtensionToken} disabled={extensionTokenLoading}>
                {extensionTokenLoading ? (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                ) : (
                  <Smartphone className="mr-2 h-4 w-4" />
                )}
                {extensionTokenPreview ? "重新生成备用 Token" : "生成备用 Token"}
              </Button>
            </div>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>个人 AI Provider</CardTitle>
          <CardDescription>
            选择一个 provider 后展开配置；模型列表优先从 provider API 拉取，失败时显示内置兜底模型。
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-5">
          <div className="grid gap-4 md:grid-cols-[minmax(0,1fr)_auto]">
            <div className="space-y-2">
              <Label htmlFor="provider-select">Provider</Label>
              <select
                id="provider-select"
                value={selectedProvider}
                onChange={(event) => {
                  setSelectedProvider(event.target.value);
                  setDefaultModel("");
                }}
                className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm"
              >
                {PROVIDER_DEFINITIONS.map((provider) => (
                  <option key={provider.id} value={provider.id}>
                    {provider.name} ({provider.category})
                  </option>
                ))}
              </select>
            </div>
            <div className="flex items-end">
              <Button variant="outline" onClick={() => setDefaultProvider(selectedProvider)}>
                设为默认
              </Button>
            </div>
          </div>

          {selectedDefinition && (
            <div className="rounded-lg border p-4">
              <div className="flex flex-wrap items-center justify-between gap-3">
                <div>
                  <div className="flex items-center gap-2">
                    <h3 className="font-semibold">{selectedDefinition.name}</h3>
                    <Badge variant="secondary">{selectedDefinition.protocol}</Badge>
                    {defaultProvider === selectedProvider && <Badge>默认</Badge>}
                  </div>
                  <p className="mt-1 text-sm text-muted-foreground">
                    {selectedStatus?.configured
                      ? `已配置 (${selectedStatus.source})`
                      : selectedRequiresGitHubLogin
                        ? "未授权，请使用 GitHub 登录授权当前账号"
                      : "未配置个人 Key，可使用环境变量或在下方填写"}
                  </p>
                </div>
                <a
                  href={selectedDefinition.docsUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-1 text-sm text-primary hover:underline"
                >
                  文档
                  <ExternalLink className="h-3.5 w-3.5" />
                </a>
              </div>

              <div className="mt-4 grid gap-4 md:grid-cols-2">
                {selectedRequiresGitHubLogin ? (
                  <div className="space-y-2">
                    <Label>GitHub 授权</Label>
                    <div className="rounded-md border bg-muted/30 p-3">
                      <p className="text-sm text-muted-foreground">
                        GitHub Copilot 使用当前 GitHub 登录账号授权，不需要输入或保存 API Key。
                      </p>
                      <Button type="button" variant="outline" className="mt-3" onClick={loginWithGitHub}>
                        <Github className="mr-2 h-4 w-4" />
                        使用 GitHub 登录授权
                      </Button>
                    </div>
                  </div>
                ) : (
                  <div className="space-y-2">
                    <Label>API Key</Label>
                    <div className="relative">
                      <Input
                        type={showKeys[selectedProvider] ? "text" : "password"}
                        placeholder={selectedDefinition.authType === "none" ? "无需 Key" : "sk-..."}
                        value={apiKeys[selectedProvider] || ""}
                        onChange={(event) =>
                          setApiKeys((current) => ({
                            ...current,
                            [selectedProvider]: event.target.value,
                          }))
                        }
                        className="pr-10"
                      />
                      <button
                        type="button"
                        onClick={() =>
                          setShowKeys((current) => ({
                            ...current,
                            [selectedProvider]: !current[selectedProvider],
                          }))
                        }
                        className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground"
                      >
                        {showKeys[selectedProvider] ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                      </button>
                    </div>
                  </div>
                )}

                <div className="space-y-2">
                  <Label>默认模型</Label>
                  <select
                    value={defaultModel}
                    onChange={(event) => setDefaultModel(event.target.value)}
                    className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm"
                  >
                    <option value="">使用 provider 默认: {selectedDefinition.defaultModel}</option>
                    {selectedModels.map((model) => (
                      <option key={model.id} value={model.id}>
                        {model.label || model.id}
                      </option>
                    ))}
                  </select>
                </div>
              </div>

              {selectedDefinition.note && (
                <p className="mt-3 text-xs text-muted-foreground">{selectedDefinition.note}</p>
              )}

              <div className="mt-4 flex flex-wrap gap-2">
                <Button
                  variant="outline"
                  onClick={() => loadProviderModels(selectedProvider)}
                  disabled={selectedModelState === "testing"}
                >
                  {selectedModelState === "testing" ? (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  ) : selectedModelState === "success" ? (
                    <Check className="mr-2 h-4 w-4 text-green-600" />
                  ) : selectedModelState === "error" ? (
                    <X className="mr-2 h-4 w-4 text-red-600" />
                  ) : (
                    <TestTube className="mr-2 h-4 w-4" />
                  )}
                  获取模型
                </Button>
                <Button
                  variant="outline"
                  onClick={() => testProvider(selectedProvider)}
                  disabled={selectedTestState === "testing"}
                >
                  {selectedTestState === "testing" ? (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  ) : selectedTestState === "success" ? (
                    <Check className="mr-2 h-4 w-4 text-green-600" />
                  ) : selectedTestState === "error" ? (
                    <X className="mr-2 h-4 w-4 text-red-600" />
                  ) : (
                    <TestTube className="mr-2 h-4 w-4" />
                  )}
                  测试连接
                  {testLatencies[selectedProvider] ? (
                    <span className="ml-2 text-xs">{testLatencies[selectedProvider]}ms</span>
                  ) : null}
                </Button>
              </div>

              {selectedModels.length > 0 && (
                <div className="mt-4 rounded-md border bg-muted/30 p-3">
                  <p className="mb-2 text-xs font-medium text-muted-foreground">
                    可用模型 ({selectedModels.length})
                  </p>
                  <div className="flex max-h-28 flex-wrap gap-1 overflow-y-auto">
                    {selectedModels.slice(0, 40).map((model) => (
                      <Badge key={model.id} variant="secondary" className="text-[10px]">
                        {model.label || model.id}
                      </Badge>
                    ))}
                  </div>
                </div>
              )}

              {(testErrors[selectedProvider] || modelErrors[selectedProvider]) && (
                <div className="mt-4 flex items-start gap-2 rounded bg-red-50 p-2 text-xs text-red-700">
                  <AlertCircle className="mt-0.5 h-3.5 w-3.5 shrink-0" />
                  <span>{testErrors[selectedProvider] || modelErrors[selectedProvider]}</span>
                </div>
              )}
            </div>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Github className="h-5 w-5" />
            GitHub Stars
          </CardTitle>
          <CardDescription>
            使用 GitHub 登录时可直接同步；用户名用于未通过 GitHub 登录时的公开 Stars 同步。
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Label>GitHub 用户名</Label>
            <Input
              placeholder="your-username"
              value={githubUsername}
              onChange={(event) => setGithubUsername(event.target.value)}
            />
          </div>
          <div className="flex flex-wrap items-center gap-3 rounded-lg border p-3">
            <Button variant="outline" onClick={() => linkIdentity("github")}>
              <Github className="mr-2 h-4 w-4" />
              使用 GitHub 登录授权
            </Button>
            <span className="text-sm text-muted-foreground">
              {githubStatus.configured
                ? githubStatus.hasEnvToken
                  ? "服务端已配置 GitHub 备用凭据"
                  : "GitHub 授权将由当前登录账号提供"
                : "请先绑定 GitHub 账号以启用私有授权能力"}
            </span>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>自动化偏好</CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <label className="flex items-center justify-between rounded-lg border p-3">
            <span>同步时自动生成 AI 描述</span>
            <input
              type="checkbox"
              checked={autoDescription}
              onChange={(event) => setAutoDescription(event.target.checked)}
            />
          </label>
          <label className="flex items-center justify-between rounded-lg border p-3">
            <span>同步后保存快照</span>
            <input
              type="checkbox"
              checked={autoSnapshot}
              onChange={(event) => setAutoSnapshot(event.target.checked)}
            />
          </label>
        </CardContent>
      </Card>
    </div>
  );
}
