import { NextRequest, NextResponse } from "next/server";
import { createClient as createServerSupabaseClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { getAuthUser, isExtensionAuthUser } from "@/lib/auth/get-user";
import {
  getEnvProviderConfigured,
  isSupportedProvider,
  PROVIDER_ENDPOINTS,
} from "@/lib/ai/provider-config";
import { getGitHubOAuthTokenFromSession, requiresGitHubOAuth } from "@/lib/ai/github-oauth";
import {
  MASKED_SECRET_PREFIX,
  encryptSecret,
  hasStoredSecret,
  maskSecret,
} from "@/lib/server/secrets";

export async function GET(request: NextRequest) {
  try {
    const { userId, user } = await getAuthUser(request);
    if (!userId) {
      return NextResponse.json({ error: "Authentication required" }, { status: 401 });
    }

    const supabase = isExtensionAuthUser(user)
      ? createAdminClient()
      : await createServerSupabaseClient();
    const { data: userSettings } = await supabase
      .from("user_settings")
      .select("*")
      .eq("user_id", userId)
      .maybeSingle();

    const apiKeys = userSettings?.api_keys || {};
    const providerStatus: Record<string, { configured: boolean; source: string }> = {};
    const githubOAuthToken = isExtensionAuthUser(user)
      ? ""
      : await getGitHubOAuthTokenFromSession().catch(() => "");

    for (const provider of Object.keys(PROVIDER_ENDPOINTS)) {
      if (requiresGitHubOAuth(provider)) {
        providerStatus[provider] = {
          configured: Boolean(githubOAuthToken),
          source: githubOAuthToken ? "github-oauth" : "none",
        };
        continue;
      }

      const hasUserKey = hasStoredSecret(apiKeys[provider]);
      const hasEnvKey = getEnvProviderConfigured(provider);
      providerStatus[provider] = {
        configured: hasUserKey || hasEnvKey,
        source: hasUserKey ? "user" : hasEnvKey ? "env" : "none",
      };
    }

    return NextResponse.json({
      defaultProvider:
        userSettings?.default_llm_provider ||
        process.env.DEFAULT_LLM_PROVIDER ||
        "deepseek",
      defaultModel: userSettings?.default_llm_model || "",
      embeddingModel:
        userSettings?.embedding_preference === "openai"
          ? `OpenAI ${process.env.OPENAI_EMBEDDING_MODEL || "text-embedding-3-small"} (384d)`
          : process.env.EMBEDDING_MODEL || "Xenova/all-MiniLM-L6-v2",
      embeddingPreference: userSettings?.embedding_preference || "local",
      providers: providerStatus,
      github: {
        configured: !!process.env.GITHUB_TOKEN,
        username: userSettings?.github_username || "",
        hasToken: false,
        hasEnvToken: !!process.env.GITHUB_TOKEN,
      },
      autoGenerateDescription: userSettings?.auto_generate_description ?? false,
      autoSnapshot: userSettings?.auto_snapshot ?? false,
      userApiKeys: Object.fromEntries(
        Object.entries(apiKeys).map(([key, value]) => [key, maskSecret(value)])
      ),
    });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

export async function PUT(request: NextRequest) {
  try {
    const { userId, user } = await getAuthUser(request);
    if (!userId) {
      return NextResponse.json({ error: "Authentication required" }, { status: 401 });
    }

    const body = await request.json();
    const supabase = isExtensionAuthUser(user)
      ? createAdminClient()
      : await createServerSupabaseClient();
    const updateData: any = { user_id: userId };

    if (body.default_llm_provider !== undefined) {
      if (typeof body.default_llm_provider !== "string" || !isSupportedProvider(body.default_llm_provider)) {
        return NextResponse.json({ error: "Invalid provider" }, { status: 400 });
      }
      updateData.default_llm_provider = body.default_llm_provider;
    }

    if (body.default_llm_model !== undefined) {
      updateData.default_llm_model =
        typeof body.default_llm_model === "string" && body.default_llm_model.trim()
          ? body.default_llm_model.trim()
          : null;
    }

    if (body.api_keys !== undefined) {
      const { data: existing } = await supabase
        .from("user_settings")
        .select("api_keys")
        .eq("user_id", userId)
        .maybeSingle();

      const newKeys = { ...(existing?.api_keys || {}) };
      for (const [key, value] of Object.entries(body.api_keys)) {
        if (value === null || value === "") {
          delete newKeys[key];
        } else if (typeof value === "string" && !value.startsWith(MASKED_SECRET_PREFIX)) {
          newKeys[key] = encryptSecret(value);
        }
      }
      updateData.api_keys = newKeys;
    }

    if (body.github_username !== undefined) {
      updateData.github_username = body.github_username;
    }
    if (body.embedding_preference !== undefined) {
      if (body.embedding_preference !== "local" && body.embedding_preference !== "openai") {
        return NextResponse.json({ error: "Invalid embedding preference" }, { status: 400 });
      }
      updateData.embedding_preference = body.embedding_preference;
    }
    if (body.auto_generate_description !== undefined) {
      updateData.auto_generate_description = body.auto_generate_description;
    }
    if (body.auto_snapshot !== undefined) {
      updateData.auto_snapshot = body.auto_snapshot;
    }

    const { data, error } = await supabase
      .from("user_settings")
      .upsert(updateData, { onConflict: "user_id" })
      .select()
      .single();

    if (error) throw error;
    return NextResponse.json({ success: true, settings: data });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
