import { NextRequest, NextResponse } from "next/server";
import { createClient as createServerSupabaseClient } from "@/lib/supabase/server";
import { getAuthUser } from "@/lib/auth/get-user";
import { getEnvProviderConfigured, PROVIDER_ENDPOINTS } from "@/lib/ai/provider-config";
import {
  MASKED_SECRET_PREFIX,
  encryptSecret,
  hasStoredSecret,
  maskSecret,
} from "@/lib/server/secrets";

export async function GET(request: NextRequest) {
  try {
    const { userId } = await getAuthUser(request);
    if (!userId) {
      return NextResponse.json({ error: "Authentication required" }, { status: 401 });
    }

    const supabase = await createServerSupabaseClient();
    const { data: userSettings } = await supabase
      .from("user_settings")
      .select("*")
      .eq("user_id", userId)
      .maybeSingle();

    const apiKeys = userSettings?.api_keys || {};
    const providerStatus: Record<string, { configured: boolean; source: string }> = {};
    for (const provider of Object.keys(PROVIDER_ENDPOINTS)) {
      const hasUserKey = hasStoredSecret(apiKeys[provider]);
      const hasEnvKey = getEnvProviderConfigured(provider);
      providerStatus[provider] = {
        configured: hasUserKey || hasEnvKey,
        source: hasUserKey ? "user" : hasEnvKey ? "env" : "none",
      };
    }

    return NextResponse.json({
      defaultProvider:
        userSettings?.default_llm_provider ||
        process.env.DEFAULT_LLM_PROVIDER ||
        "deepseek",
      embeddingModel:
        userSettings?.embedding_preference === "openai"
          ? "OpenAI text-embedding-3-small"
          : process.env.EMBEDDING_MODEL || "Xenova/all-MiniLM-L6-v2",
      embeddingPreference: userSettings?.embedding_preference || "local",
      providers: providerStatus,
      github: {
        configured: !!(hasStoredSecret(userSettings?.github_token) || process.env.GITHUB_TOKEN),
        username: userSettings?.github_username || "",
        hasToken: hasStoredSecret(userSettings?.github_token),
        hasEnvToken: !!process.env.GITHUB_TOKEN,
      },
      autoGenerateDescription: userSettings?.auto_generate_description ?? false,
      autoSnapshot: userSettings?.auto_snapshot ?? false,
      userApiKeys: Object.fromEntries(
        Object.entries(apiKeys).map(([key, value]) => [key, maskSecret(value)])
      ),
    });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

export async function PUT(request: NextRequest) {
  try {
    const { userId } = await getAuthUser(request);
    if (!userId) {
      return NextResponse.json({ error: "Authentication required" }, { status: 401 });
    }

    const body = await request.json();
    const supabase = await createServerSupabaseClient();
    const updateData: any = { user_id: userId };

    if (body.default_llm_provider !== undefined) {
      updateData.default_llm_provider = body.default_llm_provider;
    }

    if (body.api_keys !== undefined) {
      const { data: existing } = await supabase
        .from("user_settings")
        .select("api_keys")
        .eq("user_id", userId)
        .maybeSingle();

      const newKeys = { ...(existing?.api_keys || {}) };
      for (const [key, value] of Object.entries(body.api_keys)) {
        if (value === null || value === "") {
          delete newKeys[key];
        } else if (typeof value === "string" && !value.startsWith(MASKED_SECRET_PREFIX)) {
          newKeys[key] = encryptSecret(value);
        }
      }
      updateData.api_keys = newKeys;
    }

    if (body.github_username !== undefined) {
      updateData.github_username = body.github_username;
    }
    if (body.github_token !== undefined) {
      updateData.github_token =
        typeof body.github_token === "string" && body.github_token
          ? encryptSecret(body.github_token)
          : null;
    }
    if (body.embedding_preference !== undefined) {
      updateData.embedding_preference = body.embedding_preference;
    }
    if (body.auto_generate_description !== undefined) {
      updateData.auto_generate_description = body.auto_generate_description;
    }
    if (body.auto_snapshot !== undefined) {
      updateData.auto_snapshot = body.auto_snapshot;
    }

    const { data, error } = await supabase
      .from("user_settings")
      .upsert(updateData, { onConflict: "user_id" })
      .select()
      .single();

    if (error) throw error;
    return NextResponse.json({ success: true, settings: data });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
