import { NextRequest, NextResponse } from "next/server";
import { createClient as createServerSupabaseClient } from "@/lib/supabase/server";
import { getAuthUser } from "@/lib/auth/get-user";
import { getEnvProviderConfigured, PROVIDER_ENDPOINTS } from "@/lib/ai/provider-config";
import { encryptSecret, hasStoredSecret, maskSecret } from "@/lib/server/secrets";

export async function GET(request: NextRequest) {
  try {
    const { userId } = await getAuthUser(request);
    if (!userId) {
      return NextResponse.json(
        { error: "Authentication required" },
        { status: 401 }
      );
    }

    const supabase = await createServerSupabaseClient();

    // Get user settings
    const { data: userSettings } = await supabase
      .from("user_settings")
      .select("*")
      .eq("user_id", userId)
      .single();

    // Merge with environment defaults
    const envProviders = Object.fromEntries(
      Object.keys(PROVIDER_ENDPOINTS).map((provider) => [
        provider,
        getEnvProviderConfigured(provider as keyof typeof PROVIDER_ENDPOINTS),
      ])
    ) as Record<string, boolean>;

    const apiKeys = userSettings?.api_keys || {};

    // Compute combined provider status (user key OR env key)
    const providerStatus: Record<string, { configured: boolean; source: string }> = {};
    for (const p of Object.keys(envProviders)) {
      const hasUserKey = hasStoredSecret(apiKeys[p]);
      const hasEnvKey = envProviders[p];
      providerStatus[p] = {
        configured: hasUserKey || hasEnvKey,
        source: hasUserKey ? "user" : hasEnvKey ? "env" : "none",
      };
    }

    return NextResponse.json({
      defaultProvider:
        userSettings?.default_llm_provider ||
        process.env.DEFAULT_LLM_PROVIDER ||
        "deepseek",
      embeddingModel:
        userSettings?.embedding_preference === "openai"
          ? "OpenAI text-embedding-3-small"
          : process.env.EMBEDDING_MODEL || "Xenova/all-MiniLM-L6-v2",
      embeddingPreference: userSettings?.embedding_preference || "local",
      providers: providerStatus,
      github: {
        configured: !!(hasStoredSecret(userSettings?.github_token) || process.env.GITHUB_TOKEN),
        username: userSettings?.github_username || "",
        hasToken: hasStoredSecret(userSettings?.github_token),
        hasEnvToken: !!process.env.GITHUB_TOKEN,
      },
      autoGenerateDescription: userSettings?.auto_generate_description ?? false,
      autoSnapshot: userSettings?.auto_snapshot ?? false,
      // Include which keys user has set (mask them)
      userApiKeys: Object.fromEntries(
        Object.entries(apiKeys).map(([k, v]) => [
          k,
          maskSecret(v),
        ])
      ),
    });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

export async function PUT(request: NextRequest) {
  try {
    const { userId } = await getAuthUser(request);
    if (!userId) {
      return NextResponse.json(
        { error: "Authentication required" },
        { status: 401 }
      );
    }

    const body = await request.json();
    const supabase = await createServerSupabaseClient();

    // Build update data
    const updateData: any = { user_id: userId };

    if (body.default_llm_provider !== undefined) {
      updateData.default_llm_provider = body.default_llm_provider;
    }
    if (body.api_keys !== undefined) {
      // Merge with existing keys (don't overwrite unset ones)
      const { data: existing } = await supabase
        .from("user_settings")
        .select("api_keys")
        .eq("user_id", userId)
        .single();

      const existingKeys = existing?.api_keys || {};
      const newKeys = { ...existingKeys };
      for (const [k, v] of Object.entries(body.api_keys)) {
        if (v === null || v === "") {
          delete newKeys[k]; // Remove key
        } else if (typeof v === "string" && !v.startsWith("••••")) {
          newKeys[k] = encryptSecret(v);
        }
      }
      updateData.api_keys = newKeys;
    }
    if (body.github_username !== undefined) {
      updateData.github_username = body.github_username;
    }
    if (body.github_token !== undefined) {
      updateData.github_token = body.github_token
        ? encryptSecret(body.github_token)
        : null;
    }
    if (body.embedding_preference !== undefined) {
      updateData.embedding_preference = body.embedding_preference;
    }
    if (body.auto_generate_description !== undefined) {
      updateData.auto_generate_description = body.auto_generate_description;
    }
    if (body.auto_snapshot !== undefined) {
      updateData.auto_snapshot = body.auto_snapshot;
    }

    // Upsert
    const { data, error } = await supabase
      .from("user_settings")
      .upsert(updateData, { onConflict: "user_id" })
      .select()
      .single();

    if (error) throw error;

    return NextResponse.json({ success: true, settings: data });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
